# NNRT Base Policy Ruleset (v2.0)
# 
# This file exists for backwards compatibility.
# The new architecture uses profile-based composition.
# 
# Default profile: law_enforcement
# Available profiles: standard, law_enforcement
# 
# To use the new system directly, use load_profile('law_enforcement')
# or set --profile law_enforcement on the CLI.

# This file acts as a passthrough to the law_enforcement profile
# by including all the same files.

version: "2.0"
name: "base"
description: "Backwards-compatible base ruleset (delegates to law_enforcement profile)"

# This is a legacy shim - actual rules are in profile system
# Loading this file will work but prefer using profiles directly

settings:
  min_confidence: 0.7
  always_diagnose: true
  allow_override: true

# Empty rules - the loader will use law_enforcement profile by default
# when this file is loaded (see loader.py)
rules: []
