# NNRT Base Policy Ruleset
# 
# This is the default policy configuration.
# Rules are evaluated in priority order (higher = first).
# 
# Rule actions:
#   - remove: Remove the matched content entirely
#   - replace: Replace with specified text
#   - reframe: Add qualifying language
#   - flag: Add diagnostic but don't modify
#   - refuse: Block transformation if matched

version: "1.0"
name: "base"
description: "Default NNRT policy ruleset for neutral transformation"

# Global settings
settings:
  # Minimum confidence to apply automatic transformations
  min_confidence: 0.7
  # Generate diagnostics for all matches
  always_diagnose: true
  # Allow manual override of rules
  allow_override: true

# Rules are organized by category
rules:
  # ═══════════════════════════════════════════════════════════════════
  # INTENT ATTRIBUTION
  # Remove language that asserts intent or motive
  # ═══════════════════════════════════════════════════════════════════
  
  - id: intent_clearly
    category: intent_attribution
    priority: 100
    description: "Remove 'clearly' as intent intensifier"
    match:
      type: keyword
      patterns: ["clearly"]
      context: ["wanted", "intended", "meant", "tried"]
    action: remove
    
  - id: intent_obviously
    category: intent_attribution
    priority: 100
    description: "Remove 'obviously' as intent intensifier"
    match:
      type: keyword
      patterns: ["obviously"]
    action: remove

  - id: intent_intentionally
    category: intent_attribution
    priority: 100
    description: "Remove 'intentionally'"
    match:
      type: keyword
      patterns: ["intentionally", "deliberately", "purposely"]
    action: remove

  - id: intent_wanted_to
    category: intent_attribution
    priority: 90
    description: "Replace 'wanted to' with 'appeared to'"
    match:
      type: phrase
      patterns: ["wanted to", "meant to"]
    action: replace
    replacement: "appeared to"

  - id: intent_tried_harm
    category: intent_attribution
    priority: 90
    description: "Replace intent attribution in 'tried to [harm]'"
    match:
      type: phrase
      patterns: ["tried to hurt", "tried to intimidate", "tried to scare", "tried to provoke"]
    action: replace
    replacement: "appeared to harm"

  - id: intent_trying_harm
    category: intent_attribution
    priority: 90
    description: "Replace intent attribution in 'trying to [harm]'"
    match:
      type: phrase
      patterns: ["trying to hurt", "trying to intimidate", "trying to scare", "trying to provoke"]
    action: replace
    replacement: "appearing to harm"

  # Note: "tried to say/speak/breathe/move" describes actual attempts, NOT intent
  # These are preserved as factual observations

  - id: intent_on_purpose
    category: intent_attribution
    priority: 90
    description: "Remove 'on purpose'"
    match:
      type: phrase
      patterns: ["on purpose"]
    action: remove

  # ═══════════════════════════════════════════════════════════════════
  # LEGAL CONCLUSIONS
  # Remove or flag language that asserts legal conclusions
  # ═══════════════════════════════════════════════════════════════════

  - id: legal_guilty
    category: legal_conclusion
    priority: 200  # High priority - always flag
    description: "Flag assertion of guilt"
    match:
      type: keyword
      patterns: ["guilty", "innocent"]
    action: flag
    diagnostic:
      level: error
      code: LEGAL_CONCLUSION
      message: "Text contains legal conclusion that cannot be transformed"

  - id: legal_criminal
    category: legal_conclusion
    priority: 150
    description: "Reframe criminal terminology"
    match:
      type: keyword
      patterns: ["criminal", "illegal", "unlawful"]
    action: reframe
    reframe_template: "alleged {original}"

  - id: legal_assault_verb
    category: legal_conclusion
    priority: 150
    description: "Replace assault used as action verb"
    match:
      type: phrase
      patterns: ["assaulted me", "attacked me", "assaulted him", "assaulted her"]
    action: replace
    replacement: "made physical contact with me"

  - id: legal_assault_charge
    category: legal_terms
    priority: 200  # Higher priority - preserve charge language
    description: "Preserve assault when part of legal charge"
    match:
      type: phrase
      patterns: ["charged with assault", "charge of assault", "assault on", "assaulting an officer"]
    action: flag
    diagnostic:
      level: info
      code: LEGAL_CHARGE_PRESERVED
      message: "Legal charge language preserved for accuracy"

  - id: legal_brutality
    category: legal_conclusion
    priority: 150
    description: "Replace brutality terminology"
    match:
      type: keyword
      patterns: ["brutality"]
    action: replace
    replacement: "use of force"

  # Physical force - keep facts, neutral frame
  - id: physical_slam
    category: physical_force
    priority: 120
    description: "Preserve physical force facts neutrally"
    match:
      type: keyword
      patterns: ["slammed", "threw", "tackled", "shoved"]
    action: flag
    diagnostic:
      level: info
      code: PHYSICAL_FORCE_DESCRIBED
      message: "Physical force described - preserving factual content"

  - id: physical_struck
    category: physical_force
    priority: 120
    description: "Preserve being struck"
    match:
      type: keyword
      patterns: ["punched", "struck", "hit", "kicked"]
    action: flag
    diagnostic:
      level: info
      code: PHYSICAL_FORCE_DESCRIBED
      message: "Strike described - preserving factual content"

  - id: physical_grab
    category: physical_force
    priority: 120
    description: "Preserve grabbing/yanking"
    match:
      type: keyword
      patterns: ["grabbed", "yanked", "pulled", "dragged"]
    action: flag
    diagnostic:
      level: info
      code: PHYSICAL_FORCE_DESCRIBED
      message: "Physical contact described - preserving factual content"

  - id: physical_choke
    category: physical_force
    priority: 200
    description: "Preserve choking/neck restraint"
    match:
      type: keyword
      patterns: ["choked", "strangled", "neck"]
      context: ["hands", "arm", "around", "couldn't breathe"]
    action: flag
    diagnostic:
      level: warning
      code: NECK_RESTRAINT_DESCRIBED
      message: "Neck restraint described - critical evidence preserved"

  # Charges and accusations
  - id: charge_accused
    category: accusations
    priority: 100
    description: "Flag accusation language"
    match:
      type: keyword
      patterns: ["accused me of", "charged me with", "claimed I"]
    action: flag
    diagnostic:
      level: info
      code: ACCUSATION_NOTED
      message: "Accusation/charge noted - both perspectives preserved"

  # ═══════════════════════════════════════════════════════════════════
  # INTERPRETATION
  # Reframe subjective interpretations as observations
  # ═══════════════════════════════════════════════════════════════════

  - id: interp_suspicious
    category: interpretation
    priority: 80
    description: "Reframe 'suspicious'"
    match:
      type: keyword
      patterns: ["suspicious"]
    action: reframe
    reframe_template: "described as {original}"

  - id: interp_aggressive
    category: interpretation
    priority: 80
    description: "Reframe aggressive language (except in quotes)"
    match:
      type: keyword
      patterns: ["aggressive", "aggressively"]
    condition:
      context_excludes: ["direct_quote"]  # Don't reframe inside quotes
    action: reframe
    reframe_template: "described as {original}"

  - id: interp_threatening
    category: interpretation
    priority: 80
    description: "Reframe threatening language (except in quotes)"
    match:
      type: keyword
      patterns: ["threatening", "intimidating", "hostile"]
    condition:
      context_excludes: ["direct_quote"]  # Don't reframe inside quotes
    action: reframe
    reframe_template: "described as {original}"

  # ═══════════════════════════════════════════════════════════════════
  # INFLAMMATORY
  # Neutralize inflammatory language
  # ═══════════════════════════════════════════════════════════════════

  - id: inflam_profanity
    category: inflammatory
    priority: 50
    description: "Remove profanity (preserve meaning)"
    match:
      type: regex
      patterns: ["\\b(damn|hell|crap)\\b"]
    action: remove

  - id: inflam_brutal
    category: inflammatory
    priority: 80
    description: "Remove 'brutal' modifier"
    match:
      type: keyword
      patterns: ["brutal", "vicious", "ruthless"]
    action: remove

  - id: inflam_manner
    category: inflammatory
    priority: 80
    description: "Remove inflammatory manner adverbs"
    match:
      type: keyword
      patterns: ["viciously", "ruthlessly", "savagely", "mercilessly"]
    action: remove

  - id: inflam_cop
    category: inflammatory
    priority: 60
    description: "Replace 'cop' with 'officer'"
    match:
      type: keyword
      patterns: ["cop"]
    action: replace
    replacement: "officer"

  - id: inflam_derogatory_officer
    category: inflammatory
    priority: 80
    description: "Replace derogatory terms for officers"
    match:
      type: keyword
      patterns: ["thug", "pig", "goon", "bully"]
    action: replace
    replacement: "officer"

  - id: inflam_violent_modifier
    category: inflammatory
    priority: 70
    description: "Remove 'violent' as modifier (unless describing specific action)"
    match:
      type: keyword
      patterns: ["violent", "crazy", "insane", "psycho"]
    action: remove

  - id: inflam_emotional_extreme
    category: inflammatory
    priority: 60
    description: "Flag extreme emotional language"
    match:
      type: keyword
      patterns: ["destroyed my life", "ruined my life", "traumatized"]
    action: flag
    diagnostic:
      level: info
      code: EMOTIONAL_IMPACT_STATED
      message: "Emotional impact statement - preserved but noted"

  # ═══════════════════════════════════════════════════════════════════
  # PRESERVATION
  # Rules that ensure certain content is preserved
  # ═══════════════════════════════════════════════════════════════════

  - id: preserve_quotes
    category: preservation
    priority: 1000  # Highest priority
    description: "Preserve direct quotes verbatim"
    match:
      type: quoted
      patterns: ["\".*?\"", "'.*?'"]
    action: preserve
    
  - id: preserve_timestamps
    category: preservation
    priority: 900
    description: "Preserve timestamps"
    match:
      type: regex
      patterns: ["\\d{1,2}:\\d{2}\\s*(AM|PM|am|pm)?", "\\d{1,2}/\\d{1,2}/\\d{2,4}"]
    action: preserve

  # ═══════════════════════════════════════════════════════════════════
  # CONTEXT-AWARE RULES
  # These rules use conditions to modify behavior based on segment context
  # ═══════════════════════════════════════════════════════════════════

  # Preserve legal terms when in charge/accusation context
  - id: ctx_legal_in_charge
    category: context_aware
    priority: 250  # Higher than legal_conclusion rules
    description: "Preserve legal terms when describing charges"
    match:
      type: keyword
      patterns: ["assault", "battery", "robbery", "theft", "resisting"]
    condition:
      context_includes: ["charge"]  # Only when segment has charge context
    action: flag
    diagnostic:
      level: info
      code: CHARGE_TERM_PRESERVED
      message: "Legal term preserved - part of charge description"

  # Remove legal terms when NOT in charge context (normal behavior)
  - id: ctx_legal_standalone
    category: context_aware
    priority: 240
    description: "Flag legal conclusions when not describing a charge"
    match:
      type: keyword
      patterns: ["assault", "battery"]
    condition:
      context_excludes: ["charge"]  # Only when NOT in charge context
    action: flag
    diagnostic:
      level: warning
      code: LEGAL_TERM_FLAGGED
      message: "Legal conclusion language detected"

  # Preserve "tried to" in physical attempt context
  - id: ctx_physical_attempt_preserve
    category: context_aware
    priority: 250
    description: "Preserve 'tried to' when describing physical attempts"
    match:
      type: phrase
      patterns: ["tried to", "trying to"]
    condition:
      context_includes: ["physical_attempt"]
    action: preserve

  # Flag direct quotes in quote context for extra protection
  - id: ctx_quote_protection
    category: context_aware
    priority: 300
    description: "Extra protection for content in quote context"
    match:
      type: regex
      patterns: ["['\"].+?['\"]"]
    condition:
      context_includes: ["direct_quote"]
    action: preserve

  # M3: Note - Sarcasm and neutral detection is handled in p25_annotate_context
  # The pass adds INPUT_ALREADY_NEUTRAL diagnostic when all segments are neutral
  # Individual segment sarcasm is flagged via SegmentContext.SARCASM
  # Future: Add specific pattern-based rules for sarcasm handling

# Validation rules run after transformation
validation:
  - id: val_no_new_facts
    description: "Output must not contain facts not in input"
    type: subset_check
    
  - id: val_no_legal_conclusions
    description: "Output must not contain legal conclusions"
    type: forbidden_terms
    terms: ["guilty", "innocent", "convicted"]
    
  - id: val_first_person
    description: "First-person perspective must be maintained"
    type: perspective_check
